import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash,generateKeyPairSync,randomBytes,sign} from 'node:crypto';
import {verifyRegistrationResponse,verifyAuthenticationResponse,type RegistrationResponseJSON,type AuthenticationResponseJSON} from '@simplewebauthn/server';
import {isoCBOR} from '@simplewebauthn/server/helpers';
const origin='https://citizenbankapp.vercel.app',rp='citizenbankapp.vercel.app';
const b64=(b:Uint8Array)=>Buffer.from(b).toString('base64url');
const hash=(b:string|Uint8Array)=>createHash('sha256').update(b).digest();
test('real cryptographic WebAuthn verification requires correct challenge, origin, signature and local user verification',async()=>{
 const {privateKey,publicKey}=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),jwk=publicKey.export({format:'jwk'});
 const id=randomBytes(32),challenge=b64(randomBytes(32));
 const cose=isoCBOR.encode(new Map<number,any>([[1,2],[3,-7],[-1,1],[-2,new Uint8Array(Buffer.from(jwk.x!,'base64url'))],[-3,new Uint8Array(Buffer.from(jwk.y!,'base64url'))]]));
 const len=Buffer.alloc(2);len.writeUInt16BE(id.length);
 const regAuth=Buffer.concat([hash(rp),Buffer.from([0x45]),Buffer.alloc(4),Buffer.alloc(16),len,id,Buffer.from(cose)]);
 const reg:RegistrationResponseJSON={id:b64(id),rawId:b64(id),type:'public-key',clientExtensionResults:{},response:{clientDataJSON:b64(Buffer.from(JSON.stringify({type:'webauthn.create',challenge,origin}))),attestationObject:b64(isoCBOR.encode(new Map<string,any>([['fmt','none'],['attStmt',new Map()],['authData',new Uint8Array(regAuth)]])))} };
 const registration=await verifyRegistrationResponse({response:reg,expectedChallenge:challenge,expectedOrigin:origin,expectedRPID:rp,requireUserVerification:true});
 assert.equal(registration.verified,true);
 const client=Buffer.from(JSON.stringify({type:'webauthn.get',challenge,origin})),counter=Buffer.alloc(4);counter.writeUInt32BE(1);
 const authData=Buffer.concat([hash(rp),Buffer.from([5]),counter]);
 const auth:AuthenticationResponseJSON={id:b64(id),rawId:b64(id),type:'public-key',clientExtensionResults:{},response:{authenticatorData:b64(authData),clientDataJSON:b64(client),signature:b64(sign('sha256',Buffer.concat([authData,hash(client)]),privateKey))}};
 const options={response:auth,expectedChallenge:challenge,expectedOrigin:origin,expectedRPID:rp,credential:registration.registrationInfo!.credential,requireUserVerification:true};
 assert.equal((await verifyAuthenticationResponse(options)).verified,true);
 await assert.rejects(()=>verifyAuthenticationResponse({...options,expectedChallenge:'different'}));
 await assert.rejects(()=>verifyAuthenticationResponse({...options,expectedOrigin:'https://attacker.invalid'}));
 const noUV=Buffer.from(authData);noUV[32]=1;
 await assert.rejects(()=>verifyAuthenticationResponse({...options,response:{...auth,response:{...auth.response,authenticatorData:b64(noUV)}}}));
 assert.equal((await verifyAuthenticationResponse({...options,response:{...auth,response:{...auth.response,signature:b64(sign('sha256',Buffer.from('wrong-message'),privateKey))}}})).verified,false);
 await assert.rejects(()=>verifyAuthenticationResponse({...options,credential:{...options.credential,counter:1}}));
});
