-- User-approved current terms: SAFE, R10/reference share, R10,000 minimum.
-- Source: R10 SAFE template 1LOoXZ2_WvENpz0icVY-5Gi2M40UHP3oJ.
-- Register snapshot: September shareholders pack 185wh-mPPyHeKg-qlqBb8bUsWj2zjUc-4.
-- 9,554,700 is a dated uncertified register figure, NOT live available inventory.
ALTER TABLE hub_opportunities ALTER COLUMN max_units DROP NOT NULL;
ALTER TABLE hub_opportunities ADD COLUMN disclosure jsonb;
UPDATE hub_opportunities SET title='Ordinary Class B — SAFE subscription',summary='Subscribe through a SAFE in Citizen Digital Ltd (Reg. 99073), for future Ordinary Class B shares subject to the agreement’s conversion conditions. Citizen Digital Ltd is in pre-licensing and does not hold a banking licence.',instrument='SAFE',currency='ZAR',unit_price=10,min_units=1000,max_units=NULL,terms_link='https://docs.google.com/document/d/1LOoXZ2_WvENpz0icVY-5Gi2M40UHP3oJ/edit',disclosure='{"issuer":"Citizen Digital Ltd (Reg. 99073)","share_class":"Ordinary Class B","subscription_type":"SAFE","reviewed_on":"2026-10-09","register_as_of":"2026-09-26","register_unissued":9554700,"register_status":"pending_reconciliation"}'::jsonb,version=version+1 WHERE reference='safe-2026-standard' AND scope='live';
-- Reuse the genuine offer terms in the isolated demonstration, not invented share classes.
UPDATE hub_opportunities SET title='Ordinary Class B — SAFE subscription',summary='Practise the current Citizen Digital SAFE journey with the same published terms. Demonstration only: no payment, contract or shares are issued.',instrument='SAFE',currency='ZAR',unit_price=10,min_units=1000,max_units=NULL,terms_link='https://docs.google.com/document/d/1LOoXZ2_WvENpz0icVY-5Gi2M40UHP3oJ/edit',disclosure='{"issuer":"Citizen Digital Ltd (Reg. 99073)","share_class":"Ordinary Class B","subscription_type":"SAFE","reviewed_on":"2026-10-09","register_as_of":"2026-09-26","register_unissued":9554700,"register_status":"pending_reconciliation"}'::jsonb,version=version+1 WHERE reference='safe-standard-example' AND scope='demonstration';
UPDATE hub_opportunities SET status='closed',version=version+1 WHERE scope='demonstration' AND reference IN('example-ordinary','example-preference') AND status<>'closed';
INSERT INTO hub_audit(action,resource_type,resource_id,scope) SELECT 'opportunity.source_reconciled','opportunity',id::text,scope FROM hub_opportunities WHERE (reference='safe-2026-standard' AND scope='live') OR (reference='safe-standard-example' AND scope='demonstration');
